.PHONY: install run test test-watch test-coverage tests-coverage format format-check lint security typecheck build lighthouse quality

install:
	bash scripts/npm_task.sh install

run:
	bash scripts/npm_task.sh run

test:
	bash scripts/npm_task.sh test

test-watch:
	bash scripts/npm_task.sh test-watch

test-coverage:
	bash scripts/npm_task.sh test-coverage

tests-coverage:
	bash scripts/npm_task.sh tests-coverage

format:
	bash scripts/npm_task.sh format

format-check:
	bash scripts/npm_task.sh format-check

lint:
	bash scripts/npm_task.sh lint

security:
	bash scripts/npm_task.sh security

typecheck:
	bash scripts/npm_task.sh typecheck

build:
	bash scripts/npm_task.sh build

lighthouse:
	bash scripts/npm_task.sh lighthouse

quality:
	bash scripts/npm_task.sh quality
