#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shlex
import stat
import sys
import tempfile
import unicodedata
from dataclasses import dataclass
from pathlib import Path
from typing import Any


VARIABLE_NAME_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")
GROUP_NAMES = ("computed", "vars", "secrets")
CONTEXT_ENV_NAMES = {"vars": "GITHUB_ENV_VARS_JSON", "secrets": "GITHUB_SECRETS_JSON"}


@dataclass(frozen=True)
class ManifestEntry:
    name: str
    allow_empty: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render deploy runtime .env from a manifest.")
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--self-test", action="store_true")
    return parser.parse_args()


def load_context(env_name: str) -> dict[str, str]:
    raw_context = os.environ.get(env_name)
    if raw_context is None:
        return {}
    if raw_context == "":
        raise ValueError(f"{env_name} is set but empty.")

    parsed_context = json.loads(raw_context)
    if not isinstance(parsed_context, dict):
        raise ValueError(f"{env_name} must contain a JSON object.")

    context: dict[str, str] = {}
    for name, value in parsed_context.items():
        if value is None:
            continue
        if not isinstance(name, str):
            raise ValueError(f"{env_name} contains a non-string key.")
        if not isinstance(value, str):
            raise ValueError(f"{env_name}.{name} must be a string.")
        context[name] = value
    return context


def parse_manifest_entry(raw_entry: Any, group_name: str) -> ManifestEntry:
    if not isinstance(raw_entry, dict):
        raise ValueError(f"{group_name} entries must be objects.")
    if set(raw_entry) != {"name", "allowEmpty"}:
        raise ValueError(f"{group_name} entries must contain only name and allowEmpty.")

    name = raw_entry["name"]
    allow_empty = raw_entry["allowEmpty"]
    if not isinstance(name, str):
        raise ValueError(f"{group_name} entry name must be a string.")
    if VARIABLE_NAME_PATTERN.fullmatch(name) is None:
        raise ValueError(f"{group_name} entry has an invalid variable name: {name}")
    if not isinstance(allow_empty, bool):
        raise ValueError(f"{group_name}.{name}.allowEmpty must be a boolean.")
    return ManifestEntry(name=name, allow_empty=allow_empty)


def load_manifest(path: Path) -> dict[str, list[ManifestEntry]]:
    raw_manifest = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw_manifest, dict):
        raise ValueError("Manifest must be a JSON object.")
    if set(raw_manifest) != set(GROUP_NAMES):
        raise ValueError("Manifest must contain exactly computed, vars, and secrets groups.")

    manifest: dict[str, list[ManifestEntry]] = {}
    seen_names: set[str] = set()
    for group_name in GROUP_NAMES:
        raw_entries = raw_manifest[group_name]
        if not isinstance(raw_entries, list):
            raise ValueError(f"{group_name} must be a list.")
        entries = [parse_manifest_entry(raw_entry, group_name) for raw_entry in raw_entries]
        for entry in entries:
            if entry.name in seen_names:
                raise ValueError(f"Duplicate manifest variable: {entry.name}")
            seen_names.add(entry.name)
        manifest[group_name] = entries
    return manifest


def get_entry_value(
    group_name: str,
    entry: ManifestEntry,
    vars_context: dict[str, str],
    secrets_context: dict[str, str],
) -> str:
    source = {"computed": os.environ, "vars": vars_context, "secrets": secrets_context}[group_name]
    value = source.get(entry.name)
    if value is None and group_name in {"vars", "secrets"}:
        value = os.environ.get(entry.name)
    if value is None:
        raise ValueError(f"Missing required {group_name} value: {entry.name}")
    if value == "" and not entry.allow_empty:
        raise ValueError(f"{entry.name} must not be empty.")
    return value


def quote_env_value(value: str) -> str:
    for character in value:
        if unicodedata.category(character) == "Cc":
            raise ValueError("Runtime values must not contain control characters.")
    return shlex.quote(value)


def render_env(manifest: dict[str, list[ManifestEntry]]) -> str:
    vars_context = load_context(CONTEXT_ENV_NAMES["vars"])
    secrets_context = load_context(CONTEXT_ENV_NAMES["secrets"])
    lines = [
        "# Generated by infra/scripts/render_deploy_env.py.",
        "# One shell-quoted NAME=value per line; loaded only by runtime_env.py.",
    ]
    for group_name in GROUP_NAMES:
        lines.extend(("", f"# {group_name}"))
        for entry in manifest[group_name]:
            value = get_entry_value(group_name, entry, vars_context, secrets_context)
            lines.append(f"{entry.name}={quote_env_value(value)}")
    lines.append("")
    return "\n".join(lines)


def write_private_atomic(path: Path, content: str) -> None:
    temporary_path: Path | None = None
    descriptor, raw_temporary_path = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temporary_path = Path(raw_temporary_path)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary_path, path)
        temporary_path = None
        path.chmod(0o600)
        if stat.S_IMODE(path.stat().st_mode) != 0o600:
            raise OSError(f"Could not restrict {path} to mode 0600.")
        directory_descriptor = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory_descriptor)
        finally:
            os.close(directory_descriptor)
    finally:
        if temporary_path is not None:
            temporary_path.unlink(missing_ok=True)


def run_self_test() -> None:
    from runtime_env import parse_runtime_env, require_private_runtime_env

    cases = {
        "PLAIN": "value",
        "EMPTY": "",
        "SPACES": "two words",
        "SINGLE_QUOTE": "owner's value",
        "SUBSTITUTION": "$(touch must-not-run)",
        "BACKTICK": "`touch must-not-run`",
        "TRAILING_BACKSLASH": "ends-with-backslash\\",
        "HASH": "value#literal",
        "UNICODE": "Привет",
    }
    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / ".env"
        output.write_text("old\n", encoding="utf-8")
        output.chmod(0o644)
        content = "\n".join(f"{name}={quote_env_value(value)}" for name, value in cases.items())
        write_private_atomic(output, content + "\n")
        require_private_runtime_env(output)
        if parse_runtime_env(output) != cases:
            raise AssertionError("Rendered runtime environment literal round-trip failed.")
        try:
            quote_env_value("line\nbreak")
        except ValueError:
            pass
        else:
            raise AssertionError("Control characters were not rejected.")
        try:
            quote_env_value("value\u0085")
        except ValueError:
            pass
        else:
            raise AssertionError("Unicode control characters were not rejected.")


def main() -> int:
    args = parse_args()
    try:
        if args.self_test:
            run_self_test()
            return 0
        if args.manifest is None or args.output is None:
            raise ValueError("--manifest and --output are required unless --self-test is used.")
        write_private_atomic(args.output, render_env(load_manifest(args.manifest)))
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"render_deploy_env.py: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
