#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


VARIABLE_NAME_PATTERN = re.compile(r"^[A-Z][A-Z0-9_]*$")
GROUP_NAMES = ("computed", "vars", "secrets")
CONTEXT_ENV_NAMES = {
    "vars": "GITHUB_ENV_VARS_JSON",
    "secrets": "GITHUB_SECRETS_JSON",
}


@dataclass(frozen=True)
class ManifestEntry:
    name: str
    allow_empty: bool


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Render deploy runtime .env from a manifest.")
    parser.add_argument("--manifest", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def load_context(env_name: str) -> dict[str, str]:
    raw_context = os.environ.get(env_name)
    if raw_context is None:
        return {}
    if raw_context == "":
        raise ValueError(f"{env_name} is set but empty.")

    parsed_context = json.loads(raw_context)
    if not isinstance(parsed_context, dict):
        raise ValueError(f"{env_name} must contain a JSON object.")

    context: dict[str, str] = {}
    for name, value in parsed_context.items():
        if value is None:
            continue
        if not isinstance(name, str):
            raise ValueError(f"{env_name} contains a non-string key.")
        if not isinstance(value, str):
            raise ValueError(f"{env_name}.{name} must be a string.")
        context[name] = value
    return context


def parse_manifest_entry(raw_entry: Any, group_name: str) -> ManifestEntry:
    if not isinstance(raw_entry, dict):
        raise ValueError(f"{group_name} entries must be objects.")
    if set(raw_entry) != {"name", "allowEmpty"}:
        raise ValueError(f"{group_name} entries must contain only name and allowEmpty.")

    name = raw_entry["name"]
    allow_empty = raw_entry["allowEmpty"]
    if not isinstance(name, str):
        raise ValueError(f"{group_name} entry name must be a string.")
    if VARIABLE_NAME_PATTERN.fullmatch(name) is None:
        raise ValueError(f"{group_name} entry has an invalid variable name: {name}")
    if not isinstance(allow_empty, bool):
        raise ValueError(f"{group_name}.{name}.allowEmpty must be a boolean.")
    return ManifestEntry(name=name, allow_empty=allow_empty)


def load_manifest(path: Path) -> dict[str, list[ManifestEntry]]:
    raw_manifest = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(raw_manifest, dict):
        raise ValueError("Manifest must be a JSON object.")
    if set(raw_manifest) != set(GROUP_NAMES):
        raise ValueError("Manifest must contain exactly computed, vars, and secrets groups.")

    manifest: dict[str, list[ManifestEntry]] = {}
    seen_names: set[str] = set()
    for group_name in GROUP_NAMES:
        raw_entries = raw_manifest[group_name]
        if not isinstance(raw_entries, list):
            raise ValueError(f"{group_name} must be a list.")
        entries = [parse_manifest_entry(raw_entry, group_name) for raw_entry in raw_entries]
        for entry in entries:
            if entry.name in seen_names:
                raise ValueError(f"Duplicate manifest variable: {entry.name}")
            seen_names.add(entry.name)
        manifest[group_name] = entries
    return manifest


def get_entry_value(
    group_name: str,
    entry: ManifestEntry,
    vars_context: dict[str, str],
    secrets_context: dict[str, str],
) -> str:
    context_by_group = {
        "computed": os.environ,
        "vars": vars_context,
        "secrets": secrets_context,
    }
    source = context_by_group[group_name]
    value = source.get(entry.name)
    if value is None and group_name in {"vars", "secrets"}:
        value = os.environ.get(entry.name)
    if value is None:
        raise ValueError(f"Missing required {group_name} value: {entry.name}")
    if value == "" and not entry.allow_empty:
        raise ValueError(f"{entry.name} must not be empty.")
    if "\0" in value:
        raise ValueError(f"{entry.name} contains a NUL byte.")
    return value


def quote_env_value(value: str) -> str:
    escaped_value = (
        value.replace("\r", "\\r")
        .replace("\n", "\\n")
        .replace("\t", "\\t")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("`", "\\`")
    )
    return f'"{escaped_value}"'


def render_env(manifest: dict[str, list[ManifestEntry]]) -> str:
    vars_context = load_context(CONTEXT_ENV_NAMES["vars"])
    secrets_context = load_context(CONTEXT_ENV_NAMES["secrets"])
    lines = [
        "# Generated by infra/scripts/render_deploy_env.py.",
        "# Do not edit this file directly on the server.",
    ]

    for group_name in GROUP_NAMES:
        lines.append("")
        lines.append(f"# {group_name}")
        for entry in manifest[group_name]:
            value = get_entry_value(group_name, entry, vars_context, secrets_context)
            lines.append(f"{entry.name}={quote_env_value(value)}")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    args = parse_args()
    try:
        manifest = load_manifest(args.manifest)
        rendered_env = render_env(manifest)
        args.output.write_text(rendered_env, encoding="utf-8")
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"render_deploy_env.py: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
