name: Backend Docker image security

on:
  workflow_call:

jobs:
  backend-docker-image-security:
    name: Backend Docker image security
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Build, lint, and scan Docker image
        run: make security-backend-docker-image
