name: Backend pip audit
on:
  workflow_call:
permissions:
  contents: read
jobs:
  backend-pip-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7
        with:
          python-version-file: backend/pyproject.toml
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          cache-suffix: backend-pip-audit
      - run: make -C backend security-pip-audit
