name: Frontend style

on:
  workflow_call:

jobs:
  frontend-style:
    name: Frontend style
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v7
      - name: "Set up Node.js"
        uses: actions/setup-node@v7
        with:
          node-version: "24.16.0"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: "Format check"
        run: make -C frontend format-check
