name: Infrastructure security

on:
  workflow_call:

jobs:
  infra-security:
    name: Infrastructure security
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Infrastructure security
        run: make security-infra
