name: "Deploy to production"

on:
  workflow_dispatch:
    inputs:
      issue_certificates:
        description: "Issue Let's Encrypt certificates before restarting the stack"
        required: true
        type: boolean
        default: false

jobs:
  deploy:
    name: "Deploy to production"
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_deploy.yaml
    with:
      issue_certificates: ${{ inputs.issue_certificates }}
    secrets: inherit
