name: Deploy to production
on:
  workflow_dispatch:
    inputs:
      issue_certificates:
        description: Issue Let's Encrypt certificates before starting the stack
        required: true
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/_deploy.yaml
    with:
      issue_certificates: ${{ inputs.issue_certificates }}
    secrets:
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
      MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
